---

- name: "Include application_backup role"
  include_role:
    name: "voskampm.application_backup"
  vars:
    backup_app: "{{ pihole_backup_app }}"
    backup_to_backup: "{{ pihole_what_to_backup }}"
