---

- block:

  - name: Install required libselinux-python
    yum:
      name: libselinux-python
      state: present

  - name: Downloading and enable the EPEL repository definitions.
    yum:
      name: epel-release
      state: present
  when: ansible_os_family == "RedHat"
